services:
  api-dev:
    image: ${ECR_REPOSITORY_URI}:dev
    container_name: mi-app-dev
    restart: always
    ports:
      - "8081:8080"
    environment:
      - DB_ADDR=${DB_ADDR}
      - ADDR=${ADDR}
      - EXTERNAL_LINK=${EXTERNAL_LINK}
      - DB_MAX_OPEN_CONNS=${DB_MAX_OPEN_CONNS}
      - DB_MAX_IDLE_CONNS=${DB_MAX_IDLE_CONNS}
      - DB_MAX_IDLE_TIME=${DB_MAX_IDLE_TIME}
      - ENV=${ENV}
      - WHITE_LIST=${WHITE_LIST}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - FROM_RESEND_EMAIL=${FROM_RESEND_EMAIL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISS=${JWT_ISS}
      - JWT_AUD=${JWT_AUD}
      - CLERK_JWKS_URL=${CLERK_JWKS_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FRONT_URL=${FRONT_URL}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PW=${REDIS_PW}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_ENABLED=${REDIS_ENABLED}
      - OPEN_EXCHANGE_APP_ID=${OPEN_EXCHANGE_APP_ID}
      - FIREBASE_CREDENTIALS_BASE64=${FIREBASE_CREDENTIALS_BASE64}
      - FRONT_URL_E=${FRONT_URL_E}
      - AWS_REGIONR=${AWS_REGIONR}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}