BEGIN;

ALTER TABLE invoices
    ADD COLUMN IF NOT EXISTS branch_id UUID REFERENCES branch(branch_id),
    ADD COLUMN IF NOT EXISTS sub_total DECIMAL(10, 2) NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_invoices_branch_id ON invoices(branch_id);

ALTER TABLE invoice_items
    ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(5, 4) NOT NULL DEFAULT 0,    
    ADD COLUMN IF NOT EXISTS tax_amount DECIMAL(10, 2) NOT NULL DEFAULT 0, 
    ADD COLUMN IF NOT EXISTS subtotal DECIMAL(10, 2) NOT NULL DEFAULT 0,   
    ADD COLUMN IF NOT EXISTS total_line DECIMAL(10, 2) NOT NULL DEFAULT 0; 

COMMIT;