basePath: /v1
definitions:
  authdomain.CodePayload:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  authdomain.CreateUserClientPayload:
    properties:
      birth_date:
        type: string
      email:
        type: string
      first_name:
        type: string
      identity_document:
        type: string
      last_name:
        type: string
      password:
        minLength: 8
        type: string
      phone:
        type: string
    required:
    - birth_date
    - email
    - first_name
    - identity_document
    - last_name
    - password
    type: object
  authdomain.CreateUserStaffPayload:
    properties:
      birth_date:
        type: string
      email:
        type: string
      first_name:
        type: string
      identity_document:
        type: string
      last_name:
        type: string
      password:
        minLength: 8
        type: string
      phone:
        type: string
      role_name:
        type: string
    required:
    - birth_date
    - email
    - first_name
    - identity_document
    - last_name
    - password
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for VitalFit, a gym system management
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: VitalFit API
paths:
  /auth/activate:
    put:
      consumes:
      - application/json
      description: Activates a user's account using the invitation code/token.
      parameters:
      - description: Activation Code
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/authdomain.CodePayload'
      produces:
      - application/json
      responses:
        "204":
          description: User successfully activated. No content returned.
        "400":
          description: Bad request (e.g., invalid JSON payload)
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Code is invalid or expired (handled by the service layer returning
            ErrNotFound)
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error (e.g., database connection issue)
          schema:
            additionalProperties: true
            type: object
      summary: Activate user account
      tags:
      - User
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user in the system with client role
      parameters:
      - description: Register user data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authdomain.CreateUserClientPayload'
      produces:
      - application/json
      responses:
        "201":
          description: 'message: user created'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: bad response
          schema:
            additionalProperties: true
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Register New User
      tags:
      - Auth
  /auth/register-staff:
    post:
      consumes:
      - application/json
      description: Register a new user in the system with and specific role
      parameters:
      - description: Register user data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authdomain.CreateUserStaffPayload'
      produces:
      - application/json
      responses:
        "201":
          description: 'message: user created'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: bad response
          schema:
            additionalProperties: true
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Register New User Staff
      tags:
      - Auth
  /health:
    get:
      consumes:
      - application/json
      description: return status, environment and version.
      produces:
      - application/json
      responses:
        "200":
          description: Ok status and system details
          schema:
            additionalProperties: true
            type: object
      summary: verify service status
      tags:
      - System
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
