basePath: /v1
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for VitalFit, a gym system management
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: VitalFit API
paths:
  /health:
    get:
      consumes:
      - application/json
      description: return status, environment and version.
      produces:
      - application/json
      responses:
        "200":
          description: Ok status and system details
          schema:
            additionalProperties: true
            type: object
      summary: verify service status
      tags:
      - System
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
